### ISSUE TITLE
new Buffer(randomHex(), 'hex') - Gives error: "Uncaught TypeError: Invalid hex string"

### ISSUE THREAD

**Issue by seijihirao** [clubedaentrega/api-test#3]
Because the default length is 7 (odd)

**Comment by sitegui** [comment]
[It uses](https://github.com/clubedaentrega/api-test/blob/fc70dad6eefbd1947c2e4ac0cb677fdee216f66e/baseContext.js#L42) the same default length as randomStr().

Maybe change it to 8?
